import torch
import torch.nn as nn
import torch.optim as optim
from accelerate import Accelerator
from diffusers import StableDiffusionPipeline, DDPOScheduler
from torchvision import transforms
from PIL import Image
import numpy as np

# Assuming HumanPreferenceRewardModel and Discriminator are defined in a models.py or utils.py
from src.models import HumanPreferenceRewardModel, Discriminator

def train_hrpm_step(hrpm, optimizer, batch, device):
    """
    Trains the Human Preference Reward Model for one step using BPR loss.
    batch = [(img_i_pil, img_j_pil, label_i_preferred_over_j)]
    label_i_preferred_over_j: 1 if i preferred, -1 if j preferred
    """
    hrpm.train()
    optimizer.zero_grad()
    
    img_i_batch_pil, img_j_batch_pil, labels = zip(*batch)
    
    # Convert PIL images to tensors via HRPM's processor
    # Ensure hrpm.forward handles list of PIL images or batched tensors
    img_i_scores = hrpm(list(img_i_batch_pil)).squeeze()
    img_j_scores = hrpm(list(img_j_batch_pil)).squeeze()

    labels_tensor = torch.tensor(labels, dtype=torch.float32, device=device)

    # BPR Loss: -log(sigmoid(score_i - score_j))
    # We want score_i > score_j if labels_tensor is 1, and score_j > score_i if labels_tensor is -1.
    # So, labels_tensor * (score_i - score_j) should be maximized.
    loss = -torch.log(torch.sigmoid(labels_tensor * (img_i_scores - img_j_scores))).mean()
    loss.backward()
    optimizer.step()
    return loss.item()

def train_discriminator_step(discriminator, optim_d, real_images, generated_images, bce_loss):
    """
    Trains the Discriminator network for one step.
    real_images: batch of real images (tensor)
    generated_images: batch of images generated by the diffusion model (tensor)
    bce_loss: Binary Cross Entropy Loss function
    """
    discriminator.train()
    optim_d.zero_grad()

    # Train with real images
    output_real = discriminator(real_images).reshape(-1)
    loss_d_real = bce_loss(output_real, torch.ones_like(output_real))

    # Train with fake images
    output_fake = discriminator(generated_images.detach()).reshape(-1) # detach for D training
    loss_d_fake = bce_loss(output_fake, torch.zeros_like(output_fake))

    loss_d = (loss_d_real + loss_d_fake) / 2
    loss_d.backward()
    optim_d.step()
    return loss_d.item()

def train_policy_step(
    accelerator,
    unet, vae, tokenizer, text_encoder, scheduler, # Core SD components
    hrpm, discriminator, # New components
    optim_g, prompts, 
    lambda_gan=0.1, 
    use_hrpm=True, 
    use_gan_regularization=True
):
    """
    Performs one policy optimization step (conceptual DDPO-like loop).
    This function simulates the generation process and calculates the combined loss.
    """
    unet.train()
    hrpm.eval() # HRPM is used for reward, not trained in this step
    discriminator.eval() # Discriminator is used for regularization, not trained in this step

    batch_size = len(prompts)
    device = accelerator.device
    
    # 1. Simulate text embeddings
    with torch.no_grad():
        input_ids = tokenizer(prompts, return_tensors="pt", padding="max_length", truncation=True, max_length=tokenizer.model_max_length).input_ids.to(device)
        prompt_embeds = text_encoder(input_ids)[0] # Assuming text_encoder outputs tuple
    
    # 2. Simulate initial latents and denoising process
    latents = torch.randn(
        batch_size, unet.config.in_channels, 
        unet.config.sample_size, unet.config.sample_size, 
        device=device,
        generator=torch.Generator(device=device).manual_seed(np.random.randint(100000)) # for diverse latents
    )
    latents = latents * scheduler.init_noise_sigma

    # Perform a simplified denoising process (single step for conceptual demo)
    timesteps = torch.tensor([999], device=device).repeat(batch_size) # High timestep for initial noise
    
    # Predict noise (epsilon)
    noise_pred = unet(latents, timesteps, prompt_embeds).sample
    
    # A dummy "next_latent" calculation based on noise_pred for generating the image
    alpha_prod_t = scheduler.alphas_cumprod[timesteps].view(-1, 1, 1, 1)
    beta_prod_t = 1 - alpha_prod_t
    denoised_latents = (latents - noise_pred * beta_prod_t.sqrt()) / alpha_prod_t.sqrt()
    final_latents_generated = denoised_latents # Use this for decoding

    # Decode latents to images
    with torch.no_grad():
        generated_images_unnorm = vae.decode(final_latents_generated / vae.config.scaling_factor, return_dict=False)[0]
        generated_images = (generated_images_unnorm / 2 + 0.5).clamp(0, 1) # Normalize to [0,1]
        
    # Convert tensor to PIL for HRPM if HRPM expects PIL (HRPM should handle both tensor/PIL)
    generated_pil_images = [transforms.ToPILImage()(img.cpu()) for img in generated_images]

    # --- Calculate Rewards and Losses ---
    total_reward = torch.zeros(batch_size, device=device)
    gan_loss_g = torch.tensor(0.0, device=device)
    avg_hrpm_reward = 0.0
    avg_automated_reward = 0.0

    if use_hrpm:
        hrpm_scores = hrpm(generated_pil_images).squeeze() # Shape (batch_size,)
        total_reward += hrpm_scores
        avg_hrpm_reward = hrpm_scores.mean().item()
    else:
        # Simulate automated rewards (e.g., CLIP score, aesthetic score)
        automated_rewards = torch.rand(batch_size, device=device) * 2 - 1 # Dummy automated scores
        total_reward += automated_rewards
        avg_automated_reward = automated_rewards.mean().item()

    if use_gan_regularization:
        # GAN loss for Generator: Generator wants Discriminator to classify generated images as 'real'
        discriminator_output_on_fake = discriminator(generated_images).reshape(-1)
        bce_loss = nn.BCEWithLogitsLoss()
        gan_loss_g = bce_loss(discriminator_output_on_fake, torch.ones_like(discriminator_output_on_fake))

    # --- Policy Optimization ---
    policy_loss_component = -total_reward.mean()

    total_loss_g = policy_loss_component
    if use_gan_regularization:
        total_loss_g += lambda_gan * gan_loss_g # Add GAN regularization term

    accelerator.backward(total_loss_g)
    optim_g.step()
    optim_g.zero_grad()
    
    return total_loss_g.item(), avg_hrpm_reward, avg_automated_reward, gan_loss_g.item()
